---
logLevel: "INFO"
logFile: null

# Number of seconds that session remains open without any activity [20 min]
sessionDuration: 1200

# Default study when -s, --study are empty, e.g. "reference_grch37:1kG_phase3"
defaultStudy: ""

# Alias to different studies, these can be fully qualified: user@project:study
#alias:
#  1kg_grch37: hgvauser@reference_grch37:1kG_phase3
#  1kg_grch38: reference_grch38:1kG_phase3


# The default organism values can be defined here, this useful when creating a new Project
organism:
  taxonomyCode: 
  scientificName: 
  commonName: 
  assembly: 


## REST client configuration options
rest:
  host: "http://localhost:8080/opencga"
  batchQuerySize: 200
  timeout: 30000
  defaultLimit: 2000


## gRPC configuration options
grpc:
  host: "localhost:9091"


## Configure the default behaviour when query variants
variant:
  unknownGenotype: "0/0"
#   each study can have a different format
#  includeFormats:
#    1kg_grch37: "GT,AD,DP,GQ"
#  vcf:
#    header: true