{{- if .Values.mongodb.deploy.enabled -}}
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: {{ .Values.mongodb.deploy.name }}
  labels:
  {{ include "opencga.labels" . | nindent 4 }}
spec:
  members: {{ int .Values.mongodb.deploy.replicas }}
  type: ReplicaSet
  version: {{ .Values.mongodb.deploy.version }}
  security:
    authentication:
      ignoreUnknownUsers: true # users can be added to the deployment through other sources. (not through the CRD) and will not be removed by the agent.
      modes: ["SCRAM"]
    tls:
      enabled: {{ and .Values.tls.privateIssuer.enabled .Values.mongodb.ssl }}
      {{- if and .Values.tls.privateIssuer.enabled .Values.mongodb.ssl }}
      certificateKeySecretRef:
        name: {{ .Values.mongodb.deploy.certificateKeySecretRef }}
      caCertificateSecretRef:
        name: {{ .Values.tls.privateIssuer.caCertificateSecretRef }}
      {{- end }}
  statefulSet:
    spec:
      template:
        spec:
          # resources can be specified by applying an override
          # per container name.
          containers:
            - name: mongod
              resources:
                {{- toYaml .Values.mongodb.deploy.resources | nindent 16 }}
            - name: mongodb-agent
              resources:
                limits:
                  cpu: "0.2"
                  memory: 250M
                requests:
                  cpu: "0.2"
                  memory: 200M
          resources:
            {{- toYaml .Values.mongodb.deploy.resources | nindent 12 }}
          nodeSelector:
            {{- toYaml .Values.mongodb.deploy.nodeSelector | nindent 12 }}
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            resources:
              requests:
                storage: {{ .Values.mongodb.deploy.volume.size }}

  users:
    - name: {{ .Values.mongodb.user }}
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: mongodb-user-password
      roles:
        - name: root
          db: admin
        - name: clusterAdmin
          db: admin
        - name: dbAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
#    replication.replSetName: rs0
    storage.wiredTiger.engineConfig.journalCompressor: zlib
{{- end -}}