apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default
#namePrefix: dev
commonLabels:
  app: opencga

resources:
  - namespace.yaml
  - rest-deployment.yaml
  - daemon-deployment.yaml
  - fabric8-rbac.yaml
  - pv-claim.yaml
  - service.yaml

configMapGenerator:
- name: conf
  files:
  - ../../../conf/storage-configuration.yml
  - ../../../conf/opencga-env.sh
  - ../../../conf/log4j.properties
  - ../../../conf/configuration.yml
  - ../../../conf/client-configuration.yml
  - ../../../conf/hadoop/hadoop-ssh.sh

secretGenerator:
- literals:
  - password=demo
  name: installation-password
generatorOptions:
  disableNameSuffixHash: true 
  labels:
    app : opencga

