name: Deploy Docker Tools

on:
  push:
    branches:
      - develop
      - release-*
      - TASK-*
    paths:
      - opencga-app/app/cloud/docker/opencga-ext-tools/Dockerfile
  workflow_dispatch:

jobs:
  build:
    uses: opencb/java-common-libs/.github/workflows/build-java-app-workflow.yml@release-4.7.x
    with:
      maven_opts:

  deploy-docker-ext-tools:
    uses: opencb/java-common-libs/.github/workflows/deploy-docker-hub-workflow.yml@release-4.7.x
    needs: build
    with:
      cli: python3 ./build/cloud/docker/docker-build.py push --images ext-tools --tag ${{ needs.build.outputs.version }}
    secrets:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}