name: Manual deploy R builder
on:
  workflow_dispatch:

jobs:
  build:
    uses: opencb/java-common-libs/.github/workflows/build-java-app-workflow.yml@develop
    with:
      maven_opts: -P${{ vars.HADOOP_FLAVOUR }},RClient -Dopencga.war.name=opencga -Dcheckstyle.skip


  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: build-folder
          path: build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          logout: true

      - name: Extract Docker image tag from project version
        id: version
        run: |
          TAG=$(grep 'Version:' build/clients/R/DESCRIPTION | cut -d' ' -f2)
          echo "version=$TAG" >> $GITHUB_OUTPUT
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:opencga-app/app/cloud/docker/opencga-r-builder/"
          push: true
          tags: |
            opencb/opencga-r-builder:latest
            opencb/opencga-r-builder:${{ steps.version.outputs.version }}

